### ISSUE TITLE
missing yelp dataset

### ISSUE THREAD

**Issue by SeekPoint** [librahu/LGRec#1]
mldl@ub1604:~/ub16_prj/LGRec/code$ python LGRec.py 
Traceback (most recent call last):
  File "LGRec.py", line 408, in <module>
    test_ratings, negative_ratings, user_pop, item_pop, user_neighbor, item_neighbor, relation_map_label = read_data(model_config.path)
  File "LGRec.py", line 24, in read_data
    with open(path + '.train.rating') as infile:
IOError: [Errno 2] No such file or directory: '../data/yelp.train.rating'
mldl@ub1604:~/ub16_prj/LGRec/code$

**Comment by librahu** [comment]
yelp dataset is here https://github.com/librahu/Dataset-In-Papers
