### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '../data/ml-100k.label'

### ISSUE THREAD

**Issue by loveJasmine** [librahu/LGRec#2]
mldl@ub1604:~/ub16_prj/LGRec/code$ python LGRec.py 
Traceback (most recent call last):
  File "LGRec.py", line 408, in <module>
    test_ratings, negative_ratings, user_pop, item_pop, user_neighbor, item_neighbor, relation_map_label = read_data(model_config.path)
  File "LGRec.py", line 103, in read_data
    with open(path + '.label') as infile:
IOError: [Errno 2] No such file or directory: '../data/ml-100k.label'
mldl@ub1604:~/ub16_prj/LGRec/code$

**Comment by librahu** [comment]
please run the file ：get_label.py
