### ISSUE TITLE
Missing data file

### ISSUE THREAD

**Issue by tfl435918939** [librahu/LGRec#3]
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/csdc01/PycharmProjects/LGRec/code/metapathGeneration.py", line 238, in <module>
    metapathGeneration = MetapathGeneration(config)
  File "C:/Users/csdc01/PycharmProjects/LGRec/code/metapathGeneration.py", line 31, in __init__
    self.load_ua(uafile)
  File "C:/Users/csdc01/PycharmProjects/LGRec/code/metapathGeneration.py", line 178, in load_ua
    with open(uafile) as infile:
FileNotFoundError: [Errno 2] No such file or directory: '../data/ml-100k.ua'
```

**Comment by tfl435918939** [comment]
No such file or directory: '../data/ml-100k.uo'
No such file or directory: '../data/ml-100k.mt'

**Comment by tfl435918939** [comment]
Could you offer me the missing data file? Thx :)

**Comment by librahu** [comment]
dataset is available here ： https://github.com/librahu/Dataset-In-Papers

**Comment by tfl435918939** [comment]
Okay, I got that. But the data filename is confusing. Is the ''../data/ml-100k.ua'' equivalent to ''Dataset-In-Papers/Movielens/user_age.dat''?

**Comment by librahu** [comment]
yes. I rename it

**Comment by zdjohn** [comment]
which file in the new data set maps to ml-100k.mt? @librahu Thank you!

**Comment by librahu** [comment]
@zdjohn  movie_genre.dat in https://github.com/librahu/HIN-Datasets-for-Recommendation-and-Network-Embedding/tree/master/Movielens
